# Generated by Django 4.2.16 on 2026-07-17 20:10

import apps.core.encryption
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المشروع")),
                (
                    "public_slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="الرابط العام",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=280, verbose_name="وصف مختصر"),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/covers/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="الموقع"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="الولاية/المنطقة"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="خط العرض"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="خط الطول"),
                ),
                (
                    "beneficiaries_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="عدد المستفيدين"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ البدء"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", max_length=8, verbose_name="العملة"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="التكلفة التقديرية",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ المستهدف",
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ المتوفر",
                    ),
                ),
                (
                    "minimum_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="أقل مساهمة",
                    ),
                ),
                (
                    "open_contribution",
                    models.BooleanField(
                        default=True, verbose_name="السماح بمبلغ مفتوح"
                    ),
                ),
                (
                    "count_inkind_in_progress",
                    models.BooleanField(
                        default=False, verbose_name="احتساب العيني في الإنجاز"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="اسم البنك"
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم صاحب الحساب"
                    ),
                ),
                (
                    "iban",
                    apps.core.encryption.EncryptedCharField(
                        blank=True, default="", max_length=512, verbose_name="الآيبان"
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(blank=True, verbose_name="رابط الدفع"),
                ),
                (
                    "payment_instructions",
                    models.TextField(blank=True, verbose_name="تعليمات الدفع"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending_approval", "بانتظار الاعتماد"),
                            ("returned", "معاد للتعديل"),
                            ("approved", "معتمد"),
                            ("active", "نشط"),
                            ("funded", "مكتمل التمويل"),
                            ("in_progress", "قيد التنفيذ"),
                            ("suspended", "موقوف مؤقتًا"),
                            ("cancelled", "ملغى"),
                            ("closing", "طلب إغلاق"),
                            ("financial_review", "بانتظار المراجعة المالية"),
                            ("execution_review", "بانتظار المراجعة التنفيذية"),
                            ("completed", "مكتمل"),
                            ("financially_closed", "مغلق ماليًا"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "financial_progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="الإنجاز المالي",
                    ),
                ),
                (
                    "execution_progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="الإنجاز التنفيذي",
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ المحصّل",
                    ),
                ),
                (
                    "contributors_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المساهمين"
                    ),
                ),
                (
                    "contributions_enabled",
                    models.BooleanField(
                        default=True, verbose_name="استقبال المساهمات مفعّل"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, verbose_name="ملاحظة المراجعة"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ النشر"
                    ),
                ),
            ],
            options={
                "verbose_name": "مشروع",
                "verbose_name_plural": "المشاريع",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="الاسم"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="folder",
                        max_length=60,
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "تصنيف مشروع",
                "verbose_name_plural": "تصنيفات المشاريع",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المرحلة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="الوزن"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ البدء"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="النسبة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار البدء"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتملة"),
                            ("delayed", "متأخرة"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرحلة مشروع",
                "verbose_name_plural": "مراحل المشاريع",
                "ordering": ("project", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(verbose_name="المحتوى")),
                (
                    "new_progress",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="النسبة الجديدة",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "عام"), ("internal", "داخلي")],
                        default="public",
                        max_length=20,
                        verbose_name="الظهور",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "بانتظار المراجعة"),
                            ("scheduled", "مجدول"),
                            ("published", "منشور"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ النشر"
                    ),
                ),
                (
                    "notify_contributors",
                    models.BooleanField(default=False, verbose_name="إشعار المساهمين"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الكاتب",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updates",
                        to="projects.projectstage",
                        verbose_name="المرحلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحديث مشروع",
                "verbose_name_plural": "تحديثات المشاريع",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TransparencySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "show_target",
                    models.BooleanField(default=True, verbose_name="عرض الهدف"),
                ),
                (
                    "show_collected",
                    models.BooleanField(default=True, verbose_name="عرض المحصّل"),
                ),
                (
                    "show_remaining",
                    models.BooleanField(default=True, verbose_name="عرض المتبقي"),
                ),
                (
                    "show_revenues",
                    models.BooleanField(default=True, verbose_name="عرض الإيرادات"),
                ),
                (
                    "show_expenses",
                    models.BooleanField(default=True, verbose_name="عرض المصروفات"),
                ),
                (
                    "show_balance",
                    models.BooleanField(default=False, verbose_name="عرض الرصيد"),
                ),
                (
                    "show_invoices",
                    models.BooleanField(default=False, verbose_name="عرض الفواتير"),
                ),
                (
                    "show_contributor_names",
                    models.BooleanField(
                        default=False, verbose_name="عرض أسماء المساهمين"
                    ),
                ),
                (
                    "show_stages",
                    models.BooleanField(default=True, verbose_name="عرض المراحل"),
                ),
                (
                    "show_updates",
                    models.BooleanField(default=True, verbose_name="عرض التحديثات"),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transparency",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transparency_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخر تعديل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد شفافية",
                "verbose_name_plural": "إعدادات الشفافية",
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/updates/", verbose_name="الصورة"
                    ),
                ),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.projectupdate",
                        verbose_name="التحديث",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة تحديث",
                "verbose_name_plural": "صور التحديثات",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.projectcategory",
                verbose_name="التصنيف",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدير المشروع",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="organizations.organization",
                verbose_name="الجهة",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["public_slug"], name="projects_pr_public__bab58b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization"], name="projects_pr_organiz_da3a59_idx"
            ),
        ),
    ]
