# Generated by Django 4.2.16 on 2026-07-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="collected_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="المبلغ المحصّل",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="currency",
            field=models.CharField(default="OMR", max_length=8, verbose_name="العملة"),
        ),
        migrations.AlterField(
            model_name="project",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="التكلفة التقديرية",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="initial_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="المبلغ المتوفر",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="minimum_contribution",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="أقل مساهمة"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="المبلغ المستهدف",
            ),
        ),
    ]
