/**
 * Design system — "Ethos / منصة الخير".
 * Ported verbatim from UI Samples (Material-3 token set, Forest Green + Navy).
 * Brand: Transparent · Trustworthy · Methodical · RTL-first.
 */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002117",
        "status-returned": "#8B5CF6",
        "status-pending": "#F59E0B",
        "secondary-container": "#b6d0ff",
        surface: "#f7f9fb",
        "on-tertiary-fixed-variant": "#00522f",
        "inverse-on-surface": "#eff1f3",
        "primary-container": "#0d5c46",
        "surface-container-low": "#f2f4f6",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#001b3c",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002110",
        "on-primary-container": "#8cd2b6",
        "status-completed": "#0D5C46",
        "on-surface-variant": "#3f4944",
        "on-secondary": "#ffffff",
        outline: "#6f7974",
        "transparency-private": "#E2E8F0",
        "tertiary-fixed": "#91f8b8",
        "on-primary-fixed-variant": "#00513d",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed": "#d6e3ff",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#2d476f",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "on-tertiary-container": "#71d79a",
        "tertiary-fixed-dim": "#74db9d",
        "inverse-primary": "#8ed5b9",
        "primary-fixed": "#aaf1d4",
        "status-approved": "#10B981",
        "on-error-container": "#93000a",
        "inverse-surface": "#2d3133",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "status-rejected": "#EF4444",
        "on-secondary-container": "#3f5882",
        "status-draft": "#64748B",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        background: "#f7f9fb",
        "primary-fixed-dim": "#8ed5b9",
        "secondary-fixed-dim": "#adc7f7",
        "surface-dim": "#d8dadc",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#226a53",
        tertiary: "#004325",
        primary: "#004331",
        "on-error": "#ffffff",
        "outline-variant": "#bfc9c2",
        secondary: "#455f88",
        "tertiary-container": "#005d36",
        "status-delayed": "#B91C1C",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        unit: "4px",
        "container-max-width": "1280px",
        "stack-sm": "8px",
        "margin-desktop": "32px",
      },
      maxWidth: {
        "container-max-width": "1280px",
      },
      fontFamily: {
        body: ["Plus Jakarta Sans", "IBM Plex Sans Arabic", "sans-serif"],
        heading: ["IBM Plex Sans Arabic", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "IBM Plex Sans Arabic"],
        "body-md": ["Plus Jakarta Sans", "IBM Plex Sans Arabic"],
        "body-lg": ["Plus Jakarta Sans", "IBM Plex Sans Arabic"],
        "display-lg": ["IBM Plex Sans Arabic"],
        "headline-md": ["IBM Plex Sans Arabic"],
        "headline-lg": ["IBM Plex Sans Arabic"],
        "headline-sm": ["IBM Plex Sans Arabic"],
        "label-md": ["IBM Plex Sans Arabic"],
        "code-ref": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "52px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "code-ref": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      boxShadow: {
        soft: "0 4px 12px rgba(0, 0, 0, 0.04)",
        "soft-lg": "0 8px 24px rgba(0, 0, 0, 0.08)",
        "primary-glow": "0 4px 12px rgba(0, 67, 49, 0.15)",
      },
    },
  },
  plugins: [],
};
