# Generated by Django 4.2.16 on 2026-07-17 20:27

import apps.accounts.managers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "successful",
                    models.BooleanField(default=False, verbose_name="ناجحة"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="المتصفح"
                    ),
                ),
            ],
            options={
                "verbose_name": "محاولة دخول",
                "verbose_name_plural": "محاولات الدخول",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                ("code", models.CharField(max_length=8, verbose_name="الرمز")),
                (
                    "purpose",
                    models.CharField(
                        choices=[("login", "تسجيل الدخول"), ("register", "إنشاء حساب")],
                        default="login",
                        max_length=20,
                        verbose_name="الغرض",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="ينتهي في")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="المحاولات"
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="مستخدم")),
            ],
            options={
                "verbose_name": "رمز تحقق",
                "verbose_name_plural": "رموز التحقق",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم الكامل"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "مدير المنصة"),
                            ("org_manager", "مدير الجهة"),
                            ("project_owner", "صاحب المشروع"),
                            ("finance_officer", "المسؤول المالي"),
                            ("auditor", "المدقق"),
                            ("content_officer", "مسؤول المحتوى والحملات"),
                            ("contributor", "المساهم"),
                        ],
                        default="contributor",
                        max_length=30,
                        verbose_name="الدور",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="موظف إداري"),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="تم التحقق من الهاتف"
                    ),
                ),
                (
                    "notify_dues",
                    models.BooleanField(default=True, verbose_name="تذكير الاستحقاقات"),
                ),
                (
                    "notify_updates",
                    models.BooleanField(default=True, verbose_name="تحديثات المشاريع"),
                ),
                (
                    "notify_campaigns",
                    models.BooleanField(default=True, verbose_name="الحملات الترويجية"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
                "ordering": ("-date_joined",),
            },
            managers=[("objects", apps.accounts.managers.UserManager()),],
        ),
    ]
