# Generated by Django 4.2.16 on 2026-07-17 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="القيمة",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("one_time", "مرة واحدة"),
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("quarterly", "ربع سنوي"),
                            ("semiannual", "نصف سنوي"),
                            ("annual", "سنوي"),
                            ("custom", "مخصص"),
                        ],
                        default="one_time",
                        max_length=20,
                        verbose_name="الدورية",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(default=1, verbose_name="الحد الأدنى"),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الحد الأعلى"
                    ),
                ),
                (
                    "installments_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="عدد الدفعات"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_types",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع سهم",
                "verbose_name_plural": "أنواع الأسهم",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="رقم الاشتراك",
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("share", "سهم"),
                            ("open", "مبلغ مفتوح"),
                            ("subscription", "اشتراك دوري"),
                        ],
                        default="share",
                        max_length=20,
                        verbose_name="نوع المساهمة",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="عدد الأسهم"),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="قيمة الوحدة",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="إجمالي الالتزام",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المدفوع",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("one_time", "مرة واحدة"),
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("quarterly", "ربع سنوي"),
                            ("semiannual", "نصف سنوي"),
                            ("annual", "سنوي"),
                            ("custom", "مخصص"),
                        ],
                        default="one_time",
                        max_length=20,
                        verbose_name="الدورية",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                (
                    "installments_count",
                    models.PositiveIntegerField(default=1, verbose_name="عدد الدفعات"),
                ),
                (
                    "public_name_preference",
                    models.CharField(
                        choices=[
                            ("full", "الاسم الكامل"),
                            ("anonymous", "فاعل خير"),
                            ("hidden_amount", "إخفاء المبلغ"),
                        ],
                        default="anonymous",
                        max_length=20,
                        verbose_name="تفضيل إظهار الاسم",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("completed", "مكتمل"),
                            ("paused", "موقوف"),
                            ("cancelled", "ملغى"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "share_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="contributions.sharetype",
                        verbose_name="نوع السهم",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المساهم",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك",
                "verbose_name_plural": "الاشتراكات",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="التسلسل")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المدفوع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "معلّق"),
                            ("partial", "مسدّد جزئيًا"),
                            ("paid", "مسدّد"),
                            ("overdue", "متأخر"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "last_reminder_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تذكير"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="contributions.subscription",
                        verbose_name="الاشتراك",
                    ),
                ),
            ],
            options={
                "verbose_name": "استحقاق",
                "verbose_name_plural": "الاستحقاقات",
                "ordering": ("subscription", "sequence"),
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["project", "status"], name="contributio_project_3af7e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "status"], name="contributio_user_id_ec3945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installment",
            index=models.Index(
                fields=["subscription", "sequence"],
                name="contributio_subscri_f86fae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="installment",
            index=models.Index(
                fields=["status", "due_date"], name="contributio_status_d76e56_idx"
            ),
        ),
    ]
