# Generated by Django 4.2.16 on 2026-07-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installment",
            name="amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="المبلغ"
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="المدفوع"
            ),
        ),
        migrations.AlterField(
            model_name="sharetype",
            name="value",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="القيمة"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="المدفوع"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="total_value",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="إجمالي الالتزام",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="unit_value",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="قيمة الوحدة"
            ),
        ),
    ]
