# Generated by Django 4.2.16 on 2026-07-17 20:16

import apps.core.encryption
import apps.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contributions", "0001_initial"),
        ("projects", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="البند")),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ المعتمد",
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ المصروف",
                    ),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ الملتزم به",
                    ),
                ),
                (
                    "alert_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("90"),
                        max_digits=5,
                        verbose_name="حد التنبيه (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند ميزانية",
                "verbose_name_plural": "بنود الميزانية",
                "ordering": ("budget", "name"),
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=100, verbose_name="الفئة"),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم الفاتورة"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="تاريخ الفاتورة")),
                (
                    "amount_before_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ قبل الضريبة",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="مبلغ الضريبة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ الإجمالي",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ الدفع"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="طريقة الدفع"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مرجع الدفع"
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/invoices/",
                        validators=[apps.core.validators.validate_upload],
                        verbose_name="ملف الفاتورة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("under_review", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("returned", "معاد للتعديل"),
                            ("rejected", "مرفوض"),
                            ("paid", "مدفوع"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "مرتفع"),
                        ],
                        default="low",
                        max_length=10,
                        verbose_name="المستوى",
                    ),
                ),
                (
                    "budget_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="finance.budgetitem",
                        verbose_name="بند الميزانية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="projects.projectstage",
                        verbose_name="المرحلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصروف",
                "verbose_name_plural": "المصروفات",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InKindContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="المادة")),
                (
                    "category",
                    models.CharField(blank=True, max_length=100, verbose_name="الفئة"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الكمية"
                    ),
                ),
                ("unit", models.CharField(max_length=50, verbose_name="الوحدة")),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="القيمة التقديرية",
                    ),
                ),
                (
                    "external_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم المساهم الخارجي"
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "received_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="استلمها"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="الموقع"),
                ),
                (
                    "count_in_progress",
                    models.BooleanField(default=False, verbose_name="تُحتسب في التقدم"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="عامة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "مسجلة"),
                            ("pending", "بانتظار المراجعة"),
                            ("accepted", "مقبولة"),
                            ("received", "مستلمة"),
                            ("used_partial", "مستخدمة جزئيًا"),
                            ("used_full", "مستخدمة كليًا"),
                            ("rejected", "مرفوضة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inkind_contributions",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inkind",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المساهم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مساهمة عينية",
                "verbose_name_plural": "المساهمات العينية",
                "ordering": ("-date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("transfer", "تحويل"),
                            ("deposit", "إيداع"),
                            ("cash", "نقدًا"),
                            ("pos", "نقاط بيع"),
                            ("link", "رابط دفع"),
                        ],
                        default="transfer",
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مرجع التحويل"
                    ),
                ),
                (
                    "receiving_account",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الحساب المستلم"
                    ),
                ),
                (
                    "proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payments/proofs/",
                        validators=[apps.core.validators.validate_upload],
                        verbose_name="إثبات الدفع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "بانتظار المراجعة"),
                            ("approved", "معتمدة"),
                            ("returned", "معادة للاستكمال"),
                            ("rejected", "مرفوضة"),
                            ("reversed", "معكوسة"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض/الإعادة"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="مفتاح منع التكرار",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="روجعت بواسطة",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُرسلت بواسطة",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="contributions.subscription",
                        verbose_name="الاشتراك",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المساهم",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة",
                "verbose_name_plural": "الدفعات",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم")),
                (
                    "supplier_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نوع المورد"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="الهاتف"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الرقم الضريبي"
                    ),
                ),
                (
                    "commercial_register",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="السجل التجاري"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="العنوان"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم البنك"
                    ),
                ),
                (
                    "bank_account",
                    apps.core.encryption.EncryptedCharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="رقم الحساب",
                    ),
                ),
                (
                    "iban",
                    apps.core.encryption.EncryptedCharField(
                        blank=True, default="", max_length=512, verbose_name="الآيبان"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "نشط"), ("inactive", "غير نشط")],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="organizations.organization",
                        verbose_name="الجهة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد",
                "verbose_name_plural": "الموردون",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="الرمز"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإصدار"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="receipts/",
                        verbose_name="ملف الإيصال",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="finance.payment",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المساهم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إيصال",
                "verbose_name_plural": "الإيصالات",
                "ordering": ("-issued_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="إجمالي الميزانية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "بانتظار الاعتماد"),
                            ("approved", "معتمدة"),
                            ("returned", "معادة"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ملاحظة")),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "ميزانية مشروع",
                "verbose_name_plural": "ميزانيات المشاريع",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="contributions.installment",
                        verbose_name="الاستحقاق",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="finance.payment",
                        verbose_name="الدفعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "توزيع دفعة",
                "verbose_name_plural": "توزيعات الدفعات",
                "ordering": ("payment", "installment"),
            },
        ),
        migrations.CreateModel(
            name="InKindImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="inkind/", verbose_name="الصورة"),
                ),
                (
                    "contribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="finance.inkindcontribution",
                        verbose_name="المساهمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة مساهمة عينية",
                "verbose_name_plural": "صور المساهمات العينية",
            },
        ),
        migrations.CreateModel(
            name="ExpenseApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "step_role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "مدير المنصة"),
                            ("org_manager", "مدير الجهة"),
                            ("project_owner", "صاحب المشروع"),
                            ("finance_officer", "المسؤول المالي"),
                            ("auditor", "المدقق"),
                            ("content_officer", "مسؤول المحتوى والحملات"),
                            ("contributor", "المساهم"),
                        ],
                        max_length=30,
                        verbose_name="دور الخطوة",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                            ("returned", "معاد"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="القرار",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ملاحظة")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعتمد",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="finance.expense",
                        verbose_name="المصروف",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطوة اعتماد مصروف",
                "verbose_name_plural": "خطوات اعتماد المصروفات",
                "ordering": ("expense", "created_at"),
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="finance.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.projectbudget",
                verbose_name="الميزانية",
            ),
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "revenue_type",
                    models.CharField(
                        choices=[
                            ("share", "سهم"),
                            ("donation", "تبرع"),
                            ("grant", "منحة"),
                            ("corporate", "شراكة مؤسسية"),
                            ("event", "فعالية"),
                            ("other", "أخرى"),
                        ],
                        default="donation",
                        max_length=20,
                        verbose_name="نوع الإيراد",
                    ),
                ),
                (
                    "external_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم المساهم الخارجي"
                    ),
                ),
                (
                    "external_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="هاتف المساهم الخارجي"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="طريقة الدفع"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مرجع التحويل"
                    ),
                ),
                (
                    "receiving_account",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الحساب المستلم"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_public", models.BooleanField(default=False, verbose_name="عام")),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "معتمد"), ("reversed", "معكوس")],
                        default="approved",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenues",
                        to="finance.payment",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenues",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المساهم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إيراد",
                "verbose_name_plural": "الإيرادات",
                "ordering": ("-date", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="finance_rev_project_68c54e_idx",
                    ),
                    models.Index(
                        fields=["revenue_type"], name="finance_rev_revenue_be7d88_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="finance_pay_status_cb601d_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["project", "status"], name="finance_pay_project_d8c825_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["project", "status"], name="finance_exp_project_fe2a40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["tier"], name="finance_exp_tier_7e02c1_idx"),
        ),
    ]
