# Generated by Django 4.2.16 on 2026-07-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetitem",
            name="approved_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="المبلغ المعتمد",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="committed_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="المبلغ الملتزم به",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="spent_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="المبلغ المصروف",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount_before_tax",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="المبلغ قبل الضريبة",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="مبلغ الضريبة"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="المبلغ الإجمالي",
            ),
        ),
        migrations.AlterField(
            model_name="inkindcontribution",
            name="estimated_value",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="القيمة التقديرية",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="المبلغ"
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="المبلغ"
            ),
        ),
        migrations.AlterField(
            model_name="projectbudget",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="إجمالي الميزانية",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="المبلغ"
            ),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="المبلغ"
            ),
        ),
    ]
