# Generated by Django 4.2.16 on 2026-07-17 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم")),
                (
                    "campaign_type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="نوع الحملة"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "الجميع"),
                            ("active", "المساهمون النشطون"),
                            ("overdue", "المتأخرون"),
                            ("custom", "مخصص"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="الجمهور",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="النص")),
                ("link", models.URLField(blank=True, verbose_name="الرابط")),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مجدولة في"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "بانتظار الاعتماد"),
                            ("approved", "معتمدة"),
                            ("scheduled", "مجدولة"),
                            ("sending", "قيد الإرسال"),
                            ("completed", "مكتملة"),
                            ("partial", "جزئية"),
                            ("failed", "فاشلة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="projects.project",
                        verbose_name="المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "حملة",
                "verbose_name_plural": "الحملات",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="المفتاح"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
                ("body", models.TextField(verbose_name="النص")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "قالب واتساب",
                "verbose_name_plural": "قوالب واتساب",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("sent", "مُرسلة"),
                            ("failed", "فشلت"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="communications.campaign",
                        verbose_name="الحملة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_recipients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستلم حملة",
                "verbose_name_plural": "مستلمو الحملات",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="communications.whatsapptemplate",
                verbose_name="القالب",
            ),
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                ("body", models.TextField(verbose_name="النص")),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="otp/subscription/receipt/reminder/update/campaign",
                        max_length=30,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("sending", "قيد الإرسال"),
                            ("sent", "مُرسلة"),
                            ("failed", "فشلت"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المحاولات"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=5, verbose_name="الحد الأقصى للمحاولات"
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="المرجع الخارجي"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="الخطأ")),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مجدولة في"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="أُرسلت في"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="communications.campaign",
                        verbose_name="الحملة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbox_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة صادرة",
                "verbose_name_plural": "الرسائل الصادرة (Outbox)",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="communicati_status_e2b0cb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(blank=True, verbose_name="النص")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="الرابط"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="communicati_user_id_8fd9c3_idx",
                    )
                ],
            },
        ),
    ]
