# Generated by Django 4.2.16 on 2026-07-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=8)),
                ("year", models.PositiveIntegerField()),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "متسلسلة مرجعية",
                "verbose_name_plural": "المتسلسلات المرجعية",
                "unique_together": {("prefix", "year")},
            },
        ),
    ]
