# Generated by Django 4.2.16 on 2026-07-18 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إنشاء"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                            ("approve", "اعتماد"),
                            ("reject", "رفض"),
                            ("return", "إعادة"),
                            ("submit", "إرسال"),
                            ("login", "دخول"),
                            ("logout", "خروج"),
                            ("reverse", "عكس"),
                            ("export", "تصدير"),
                            ("send", "إرسال رسالة"),
                            ("close", "إغلاق"),
                        ],
                        max_length=20,
                        verbose_name="العملية",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=80, verbose_name="نوع الكيان"),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="معرّف الكيان"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="وصف مختصر"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="القيم السابقة"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="القيم الجديدة"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="متصفح المستخدم"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجل التدقيق",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="audit_audit_created_6e540c_idx"
                    ),
                ],
            },
        ),
    ]
