# Generated by Django 4.2.16 on 2026-07-17 20:10

import apps.core.encryption
import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم")),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("committee", "لجنة"),
                            ("association", "جمعية"),
                            ("foundation", "مؤسسة"),
                            ("individual", "فرد"),
                            ("team", "فريق"),
                        ],
                        default="association",
                        max_length=20,
                        verbose_name="نوع الجهة",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="orgs/logos/",
                        verbose_name="الشعار",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="الموقع"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم البنك"
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم صاحب الحساب"
                    ),
                ),
                (
                    "iban",
                    apps.core.encryption.EncryptedCharField(
                        blank=True, default="", max_length=512, verbose_name="الآيبان"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "بانتظار التحقق"),
                            ("approved", "معتمدة"),
                            ("returned", "معادة للتعديل"),
                            ("rejected", "مرفوضة"),
                            ("suspended", "موقوفة"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, verbose_name="ملاحظة المراجعة"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "جهة",
                "verbose_name_plural": "الجهات",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "file",
                    models.FileField(
                        upload_to="orgs/docs/",
                        validators=[apps.core.validators.validate_upload],
                        verbose_name="الملف",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="organizations.organization",
                        verbose_name="الجهة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند جهة",
                "verbose_name_plural": "مستندات الجهات",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "مدير المنصة"),
                            ("org_manager", "مدير الجهة"),
                            ("project_owner", "صاحب المشروع"),
                            ("finance_officer", "المسؤول المالي"),
                            ("auditor", "المدقق"),
                            ("content_officer", "مسؤول المحتوى والحملات"),
                            ("contributor", "المساهم"),
                        ],
                        max_length=30,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organizations.organization",
                        verbose_name="الجهة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو جهة",
                "verbose_name_plural": "أعضاء الجهات",
                "ordering": ("-created_at",),
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["status"], name="organizatio_status_295901_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["org_type"], name="organizatio_org_typ_ac5ef8_idx"
            ),
        ),
    ]
